name = "good-enough"
author = "nitedani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61704b48cb90ae2256b6ede763d3ffe425792816f8487a4b33c3c355903e84ae"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
