name = "good-enough"
author = "nitedani"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34dcdc624cbd09ee1bb201cb34ca786a588e2c2a1e9a3726d61651964eddebe0"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
