name = "good-enough"
author = "nitedani"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac50a96ada4c39434c169279fece9c4c43ad8261cac2ebf0fc80ad9ee3dfa87a"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
