name = "good-enough"
author = "nitedani"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eaef93b2d2e88d5df8dfb2c49b837658135348248501f229033f143fee5547cd"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
