name = "good-enough"
author = "nitedani"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70491cd733a309a9fc9d9628b1d0f8e783d5ea6513972c895ede574bad5f8b18"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
