name = "Photon Shader"
filename = "photon-main.zip"
side = "client"

[download]
url = "https://github.com/sixthsurge/photon/archive/refs/heads/main.zip"
hash-format = "sha1"
hash = "8dc120231db9c381fd0bf5b5f5ae67207291cc84"